name: nprtest
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.42.0=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.2=hd590300_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.9.17=h0755675_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=68.1.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - alabaster==0.7.16
      - annotated-types==0.7.0
      - app-model==0.2.7
      - appdirs==1.4.4
      - asttokens==2.4.1
      - astunparse==1.6.3
      - attrs==23.2.0
      - babel==2.15.0
      - blinker==1.8.2
      - build==1.2.1
      - cachetools==5.3.3
      - cachey==0.2.1
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - dash==2.18.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dask==2024.6.1
      - deap==1.4.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - docstring-parser==0.16
      - docutils==0.21.2
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - fire==0.6.0
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - freetype-py==2.4.0
      - fsspec==2024.6.0
      - gast==0.4.0
      - google-auth==2.30.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.64.1
      - h5py==3.11.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - idna==3.7
      - igraph==0.11.6
      - imageio==2.34.1
      - imagesize==1.4.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.4
      - in-n-out==0.2.1
      - ipykernel==6.29.4
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - keras==2.11.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.43.0
      - locket==1.0.0
      - lxml==5.3.0
      - lxml-html-clean==0.3.1
      - magicgui==0.8.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mrcfile==1.5.0
      - napari==0.4.19.post1
      - napari-console==0.0.9
      - napari-mrcfile-reader==0.2.0
      - napari-plugin-engine==0.2.0
      - napari-svg==0.1.10
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - npe2==0.7.5
      - numba==0.60.0
      - numpy==1.26.4
      - numpydoc==1.7.0
      - oauthlib==3.2.2
      - open3d==0.18.0
      - opt-einsum==3.3.0
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - partd==1.4.2
      - pexpect==4.9.0
      - pillow==10.3.0
      - pint==0.23
      - platformdirs==4.2.2
      - plotly==5.24.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.47
      - protobuf==3.19.6
      - psutil==6.0.0
      - psygnal==0.11.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyconify==0.1.6
      - pydantic==2.7.4
      - pydantic-compat==0.1.2
      - pydantic-core==2.18.4
      - pygments==2.18.0
      - pyopengl==3.1.7
      - pyparsing==3.1.4
      - pyproject-hooks==1.1.0
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.14
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - shellingham==1.5.4
      - simpleitk==2.3.1
      - six==1.16.0
      - snowballstemmer==2.2.0
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - splipy==1.8.2
      - stack-data==0.6.3
      - superqt==0.6.7
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-estimator==2.11.0
      - tensorflow-gpu==2.11.0
      - tensorflow-io-gcs-filesystem==0.37.0
      - termcolor==2.4.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2024.6.18
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - tslearn==0.6.3
      - typer==0.12.3
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - vispy==0.14.3
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - zipp==3.19.2
prefix: /home/lvzy/miniconda3/envs/nprtest
