name: segVesicle
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.42.0=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.2=hd590300_0
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.9.17=h0755675_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=68.1.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - alabaster==0.7.13
      - app-model==0.2.0
      - appdirs==1.4.4
      - asciitree==0.3.3
      - asttokens==2.2.1
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - build==0.10.0
      - cachey==0.2.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - comm==0.1.4
      - contourpy==1.2.1
      - cryohub==0.6.4
      - cryotypes==0.2.0
      - cycler==0.12.1
      - dask==2023.8.1
      - debugpy==1.6.7.post1
      - decorator==5.1.1
      - docstring-parser==0.15
      - docutils==0.17.1
      - dynamotable==0.2.4
      - einops==0.7.0
      - emfile==0.3.0
      - executing==1.2.0
      - fasteners==0.19
      - fire==0.6.0
      - fonttools==4.51.0
      - freetype-py==2.4.0
      - fsspec==2023.6.0
      - h5py==3.10.0
      - heapdict==1.0.1
      - hsluv==5.0.3
      - idna==3.4
      - imagecodecs==2023.9.18
      - imageio==2.31.1
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.4.0
      - in-n-out==0.1.8
      - ipykernel==6.25.1
      - ipython==8.14.0
      - ipython-genutils==0.2.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - locket==1.0.0
      - magicgui==0.7.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - morphosamplers==0.0.10
      - mrcfile==1.4.3
      - mypy-extensions==1.0.0
      - napari==0.4.18
      - napari-console==0.0.8
      - napari-mrcfile-reader==0.2.0
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.0a2
      - napari-svg==0.1.10
      - nest-asyncio==1.5.7
      - networkx==3.1
      - npe2==0.7.2
      - numcodecs==0.12.1
      - numpy==1.25.2
      - numpydoc==1.5.0
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - partd==1.4.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - pint==0.22
      - platformdirs==3.10.0
      - pooch==1.7.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.5
      - psygnal==0.9.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pydantic==1.10.12
      - pygments==2.16.1
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pyproject-hooks==1.0.0
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.2
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - referencing==0.30.2
      - requests==2.31.0
      - rich==13.5.2
      - rpds-py==0.9.2
      - scikit-image==0.21.0
      - scipy==1.11.2
      - six==1.16.0
      - snowballstemmer==2.2.0
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.2
      - starfile==0.5.2
      - superqt==0.5.3
      - termcolor==2.4.0
      - tifffile==2023.8.12
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.9.0
      - typer==0.9.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==2.0.4
      - vispy==0.12.2
      - wcwidth==0.2.6
      - wrapt==1.15.0
      - zarr==2.16.1
      - zipp==3.16.2
prefix: /home/zhenhang/anaconda3/envs/napari
